from yfantasy_api.api import YahooFantasyApi
from TradeAnalyzer import get_league, get_team_rank, get_player_rank
import csv
from datetime import datetime

team = [
"Connor McDavid",
"Auston Matthews",
"Leon Draisaitl",
"Nathan MacKinnon",
"Roman Josi",
"Cale Makar",
"Mikko Rantanen",
"Kirill Kaprizov",
"David Pastrnak",
"Juuse Saros",
"Jacob Markstrom",
"Victor Hedman",
"Alex Ovechkin",
"Nikita Kucherov",
"Andrei Vasilevskiy",
"Igor Shesterkin",
"Kyle Connor",
"Matthew Tkachuk",
"Connor Hellebuyck",
"John Carlson",
"Timo Meier",
"Patrick Kane",
"Mitch Marner",
"Thatcher Demko",
"Adam Fox",
"Moritz Seider",
"Jake Oettinger",
"Sergei Bobrovsky",
"Kris Letang",
"Jonathan Huberdeau",
"Nikolaj Ehlers",
"Steven Stamkos",
"Frederik Andersen",
"Aleksander Barkov",
"Aaron Ekblad",
"Jordan Binnington",
"Jake Guentzel",
"Kevin Fiala",
"Quinn Hughes",
"Johnny Gaudreau",
"Dougie Hamilton",
"Alexandar Georgiev",
"Darcy Kuemper",
"Sidney Crosby",
"J.T. Miller",
"Marc-Andre Fleury",
"Matt Murray",
"William Nylander",
"Filip Forsberg",
"Ilya Sorokin",
"Morgan Rielly",
"Artemi Panarin",
"Brent Burns",
"Tristan Jarry",
"Brady Tkachuk",
"Evan Bouchard",
"Elvis Merzlikins",
"Gabriel Landeskog",
"Sebastian Aho",
"Jason Robertson",
"Seth Jones",
"Carter Hart",
"Shea Theodore",
"Andrei Svechnikov",
"John Gibson",
"Alex Pietrangelo",
"John Tavares",
"Jack Campbell",
"Rasmus Dahlin",
"Noah Dobson",
"Alex DeBrincat",
"Zach Werenski",
"Thomas Chabot",
"Patrice Bergeron",
"Jack Eichel",
"Chris Kreider",
"Mika Zibanejad",
"Elias Lindholm",
"Miro Heiskanen",
"Darnell Nurse",
"Matt Boldy",
"Mark Scheifele",
"Devon Toews",
"Brayden Point",
"Roope Hintz",
"Joe Pavelski",
"Matt Duchene",
"Bryan Rust",
"Tim Stutzle",
"Vladimir Tarasenko",
"Torey Krug",
"Jeremy Swayman",
"Jake Allen",
"Jonathan Marchessault",
"Jakob Chychrun",
"Josh Morrissey",
"Cole Caufield",
"Evander Kane",
"Philipp Grubauer",
"Drew Doughty",
"Sam Reinhart",
"Nazem Kadri",
"Pavel Buchnevich",
"Jack Hughes",
"Matty Beniers",
"David Perron",
"John Klingberg",
"Ville Husso",
"Rasmus Andersson",
"Owen Power",
"Erik Karlsson",
"Cam Talbot",
"Mats Zuccarello",
"Elias Pettersson",
"Tyler Toffoli",
"Vince Dunn",
"Mikhail Sergachev",
"Jacob Trouba",
"Jared Spurgeon",
"Trevor Zegras",
"Jordan Kyrou",
"Vitek Vanecek",
"Evgeny Kuznetsov",
"Lucas Raymond",
"Patrik Laine",
"Jonathan Quick",
"James Reimer",
"MacKenzie Weegar",
"Mark Stone",
"Josh Norris",
"Evgeni Malkin",
"Justin Faulk",
"Pierre-Luc Dubois",
"Teuvo Teravainen",
"Andre Burakovsky",
"Tomas Hertl",
"Jesper Bratt",
"Karel Vejmelka",
"Travis Konecny",
"Tyler Seguin",
"Zach Hyman",
"Brad Marchand",
"Mike Matheson",
"Ivan Provorov",
"Tony DeAngelo",
"Noah Hanifin",
"Tage Thompson",
"Adrian Kempe",
"Shayne Gostisbehere",
"Ryan Nugent-Hopkins",
"Jaccob Slavin",
"Anze Kopitar",
"Mark Giordano",
"Tyson Barrie",
"Jeff Petry",
"Valeri Nichushkin",
"Logan Thompson",
"Dylan Larkin",
"Craig Anderson",
"Nick Suzuki",
"Viktor Arvidsson",
"Jake Sanderson",
"Ryan Pulock",
"Brock Boeser",
"Neal Pionk",
"Matt Dumba",
"Damon Severson",
"Bo Horvat",
"Blake Wheeler",
"Charlie McAvoy",
"Taylor Hall",
"Linus Ullmark",
"Clayton Keller",
"Andrew Mangiapane",
"Sam Bennett",
"Joel Eriksson Ek",
"Alex Killorn",
"Tyler Bertuzzi",
"Ryan Hartman",
"Jonas Brodin",
"Alex Tuch",
"Claude Giroux",
"Colton Parayko",
"Mathew Barzal",
"Nick Schmaltz",
"Vincent Trocheck",
"Oliver Bjorkstrand",
"MacKenzie Blackwood",
"Troy Terry",
"Drake Batherson",
"Cam Atkinson",
"Oliver Ekman-Larsson",
"Gustav Forsling",
"Mattias Ekholm",
"Petr Mrazek",
"Ilya Samsonov",
"Brady Skjei",
"Jeff Skinner",
"Dmitry Orlov",
"Brock Nelson",
"Conor Garland",
"T.J. Oshie",
"Logan Couture",
"Alex Stalock",
"Ryan O'Reilly",
"Anton Forsberg",
"Sean Durzi",
"Brett Pesce",
"Brandon Montour",
"Alexis Lafreniere",
"Cal Petersen",
"Cam Fowler",
"Jamie Drysdale",
"Samuel Girard",
"Sean Couturier",
"Bowen Byram",
"Filip Hronek",
"Jared McCann",
"Chris Wideman",
"Ryan Graves",
"Jakub Vrana",
"Filip Gustavsson",
"Robert Thomas"
]

def PrintRankings():
    print(f'\n\n\n\n\n\n')
    print("STARTING PROCESSING TO CSV")

    time = datetime.today().strftime('%Y-%m-%d-%S')
    fileName = './rankings/PlayersRichValRankings-' + time + '.csv'

    outfile = open(fileName,'w')
    writer=csv.writer(outfile)
    writer.writerow(['Player', 'Position', 'PreVORP', 'RichVal'])

    for player_name in team:
        get_player_rank(player_name, "CSV", writer)

    print("CSV HAS BEEN PROCESSED")
    print(f'\n\n\n\n\n\n')

    return fileName

PrintRankings()